apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
        {{- include "operator-for-redis.labels" . | nindent 4 }}
  name: {{ include "operator-for-redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
        {{- include "operator-for-redis.labels" . | nindent 4 }}
  name: redis-cluster-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
        {{- include "operator-for-redis.labels" . | nindent 4 }}
  creationTimestamp: null
  name: redis-cluster-manager-role
rules:
  - apiGroups:
      - apps
    resources:
      - controllerrevision
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.bob.com
    resources:
      - redisclusterbackups
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.bob.com
    resources:
      - redisclusterbackups/finalizers
    verbs:
      - update
  - apiGroups:
      - operator.bob.com
    resources:
      - redisclusterbackups/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - operator.bob.com
    resources:
      - redisclusterrecovers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.bob.com
    resources:
      - redisclusterrecovers/finalizers
    verbs:
      - update
  - apiGroups:
      - operator.bob.com
    resources:
      - redisclusterrecovers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - operator.bob.com
    resources:
      - redisclusterslots
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.bob.com
    resources:
      - redisclusterslots/finalizers
    verbs:
      - update
  - apiGroups:
      - operator.bob.com
    resources:
      - redisclusterslots/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - operator.bob.com
    resources:
      - redisclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.bob.com
    resources:
      - redisclusters/finalizers
    verbs:
      - update
  - apiGroups:
      - operator.bob.com
    resources:
      - redisclusters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
        {{- include "operator-for-redis.labels" . | nindent 4 }}
  name: redis-cluster-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
        {{- include "operator-for-redis.labels" . | nindent 4 }}
  name: redis-cluster-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
        {{- include "operator-for-redis.labels" . | nindent 4 }}
  name: redis-cluster-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redis-cluster-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "operator-for-redis.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
        {{- include "operator-for-redis.labels" . | nindent 4 }}
  name: redis-cluster-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redis-cluster-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "operator-for-redis.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
        {{- include "operator-for-redis.labels" . | nindent 4 }}
  name: redis-cluster-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redis-cluster-proxy-role
subjects:
  - kind: ServiceAccount
    name: {{ include "operator-for-redis.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
data:
  controller_manager_config.yaml: "apiVersion: controller-runtime.sigs.k8s.io/v1alpha1\nkind: ControllerManagerConfig\nhealth:\n  healthProbeBindAddress: :8081\nmetrics:\n  bindAddress: 127.0.0.1:8080\nwebhook:\n  port: 9443\nleaderElection:\n  leaderElect: true\n  resourceName: db753e10.bob.com\n#   leaderElectionReleaseOnCancel defines if the leader should step down volume \n#   when the Manager ends. This requires the binary to immediately end when the\n#   Manager is stopped, otherwise, this setting is unsafe. Setting this significantly\n#   speeds up voluntary leader transitions as the new leader don't have to wait\n#   LeaseDuration time first.\n#   In the default scaffold provided, the program ends immediately after \n#   the manager stops, so would be fine to enable this option. However, \n#   if you are doing or is intended to do any operation such as perform cleanups \n#   after the manager stops then its usage might be unsafe.\n#   leaderElectionReleaseOnCancel: true\n"
kind: ConfigMap
metadata:
  labels:
      {{- include "operator-for-redis.labels" . | nindent 4 }}
  name: redis-cluster-manager-config
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "operator-for-redis.labels" . | nindent 4 }}
  name: {{ include "operator-for-redis.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    {{- include "operator-for-redis.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
        {{- include "operator-for-redis.labels" . | nindent 4 }}
  name: {{ include "operator-for-redis.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app.kubernetes.io/name: {{ include "operator-for-redis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
        {{- include "operator-for-redis.labels" . | nindent 4 }}
  name: redis-cluster-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ include "operator-for-redis.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ include "operator-for-redis.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
    - host.docker.internal
  issuerRef:
    kind: Issuer
    name: redis-cluster-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
        {{- include "operator-for-redis.labels" . | nindent 4 }}
  name: redis-cluster-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
        {{- include "operator-for-redis.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/redis-cluster-serving-cert
  name: {{ include "operator-for-redis.fullname" . }}-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
{{/*      url: https://host.docker.internal:9443/mutate-operator-bob-com-v1alpha1-rediscluster*/}}
      service:
        name: {{ include "operator-for-redis.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-operator-bob-com-v1alpha1-rediscluster
    failurePolicy: Fail
    name: mrediscluster.kb.io
    rules:
      - apiGroups:
          - operator.bob.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - redisclusters
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
        {{- include "operator-for-redis.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/redis-cluster-serving-cert
  name: {{ include "operator-for-redis.fullname" . }}-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
{{/*      url: https://host.docker.internal:9443/validate-operator-bob-com-v1alpha1-rediscluster*/}}
      service:
        name: {{ include "operator-for-redis.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-operator-bob-com-v1alpha1-rediscluster
    failurePolicy: Fail
    name: vrediscluster.kb.io
    rules:
      - apiGroups:
          - operator.bob.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - redisclusters
    sideEffects: None
