apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rediscluster-servicemonitor
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - basicAuth:
      password:
        key: password
        name: redis-cluster-exporter-auth
      username:
        key: user
        name: redis-cluster-exporter-auth
    port: metrics
    interval: 15s
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      redis-operator.bob.com/cluster-type:  rediscluster
