apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator-for-redis.fullname" . }}
  labels: {{- include "operator-for-redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "operator-for-redis.selectorLabels" . | nindent 4 }}
