# Default values for operator-for-redis-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
#  repository: 172.16.5.67/redis/redisclusteroperator:v1.0.4
  repository: dev.repo.bj.bob/public-docker-baseimage-local/func/redis-cluster-operator:v1.1.5
  pullPolicy: IfNotPresent
rbacProxyImage:
  repository: dev.repo.bj.bob/public-docker-baseimage-local/func/kube-rbac-proxy:v0.11.0
  pullPolicy: IfNotPresent
Redis5DefaultImage:
  repository: dev.repo.bj.bob/public-docker-baseimage-local/func/redis:5.0
Redis6DefaultImage:
  repository: dev.repo.bj.bob/public-docker-baseimage-local/func/redis:6.2.17
RedisNodeDefaultImage:
  repository: dev.repo.bj.bob/public-docker-baseimage-local/func/redis-cluster-node:v1.1.0
RedisExporterDefaultImage:
  repository: dev.repo.bj.bob/public-docker-baseimage-local/func/redis_exporter:v1.3.5-alpine
RedisS3cmdDefaultImage:
  repository: dev.repo.bj.bob/public-docker-baseimage-local/func/s3cmd:v3.0.0
RedisAlpineDefaultImage:
  repository: dev.repo.bj.bob/public-docker-baseimage-local/func/alpine:3.15.0
toolsImage: dev.repo.bj.bob/public-docker-baseimage-local/func/redis_tools:v0.2.7
topkeyImage: dev.repo.bj.bob/public-docker-baseimage-local/func/redis_topkeys:v0.2.1

CycleTime: 20
BackupCycleTime: 900

StatusConcurrent: 20
ClusterConcurrent: 10

xc:
  enable: true

# Default args passed to the operator
args: [
  "--logtostderr=true",
  "--alsologtostderr"
]

logLevel: -1
strategy:
  type: Recreate

# Extra args to be passed to the operator
extraArgs: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  metricsPort: 2112

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

livenessProbe:
  httpGet:
    path: /healthz
    port: health
  initialDelaySeconds: 30

readinessProbe:
  httpGet:
    path: /readyz
    port: health
  initialDelaySeconds: 5

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

zoneAwareReplication: true

metrics:
  grafanaDashboard:
    enabled: false
    namespace: ""
    labels:
      grafana_dashboard: "1"
    datasourceName: ""
  serviceMonitor:
    enabled: false
    namespace: ""
    labels:
      operator: redis-operator
    scrapeInterval: 30s
